set_project("jitperm")
set_version("0.1.0")
set_languages("c++23")

add_rules("mode.debug", "mode.release")
add_requires("asmjit")

target("jitperm")
    set_kind("static")
    add_files("src/**/*.cpp")
    add_packages("asmjit")
    add_includedirs("src", {private = true})
    add_cxxflags("-Wall", "-Wextra", "-Wpedantic", "-Werror")

target("example")
    set_kind("binary")
    add_files("example/main.cpp")
    add_deps("jitperm")
    add_packages("asmjit")
    add_includedirs("src")
    add_cxxflags("-Wall", "-Wextra", "-Wpedantic", "-Werror")

target("benchmark")
    set_kind("binary")
    add_files("benchmark/benchmark.cpp")
    add_deps("jitperm")
    add_packages("asmjit")
    add_includedirs("src")
    add_cxxflags("-Wall", "-Wextra", "-Wpedantic", "-Werror")
